---

- hosts: all
  become: true
  tasks:

  - name: update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install Apache, PHP support and Htop
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"
