---

- hosts: all
  become: true
  tasks:

  - name: update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Create oga user
    tags: always
    user:
      name: oga
      groups: root

  - name: Add ssh key for Oga
    tags: always
    authorized_key:
      user: oga
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHTH3V4MmFezA/1i9WJg4wmpjuWeMOH/z9QHXpFYKt/7 ansible.pub"

  - name: Add a sudoer file for oga
    tags: always
    copy:
      src: sudoer_oga
      dest: /etc/sudoers.d/oga
      owner: root
      group: root
      mode: 0440



  - name: Start httpd (Rocky)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"


  - name: install Apache, PHP support and Htop
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Unzip
    package:
      name: unzip

  - name: Install OpenTofu
    unarchive:
      src: https://github.com/opentofu/opentofu/releases/download/v1.6.0-rc1/tofu_1.6.0-rc1_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
