- name: Install MariaDB (Rocky)
  tags: db,mariadb,rocky
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: Install MariaDB (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
